# Dependencies
markdown:            kramdown
highlighter:         rouge
# plugins:
#   - jekyll-sitemap

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title
# relative_permalinks: true

# Setup
title:               Catskull Games
tagline:             'New games for old consoles'
description:         'New games for old consoles including Nintendo Gameboy and more!'
url:                 http://catskullgames.com
baseurl:             /

# About/contact
author:
  name:              David DeGraw
  url:               https://catskullgames.com
  email:             support@catskullelectronics.com

# Custom vars
version:             1.0.0
